name: videos-j-1-10
on:
  schedule:
    - cron: "* */4 * * *"
  workflow_dispatch:
jobs:
  workflow_dispatch:
    runs-on: ubuntu-22.04
    steps:
      - name: Checking out repository code
        uses: actions/checkout@v3
        with:
          ref: videos
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Configuring git
        run: |
          git config --global user.email "fetvguide@gmail.com"
          git config --global user.name "FETVGUIDE"
      - name: Install youtube-dl
        run: |
          sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
          sudo chmod a+rx /usr/local/bin/yt-dlp
      - name: Install phamtomjs
        run: |
          curl -L https://raw.githubusercontent.com/FETVGuide/videos/main/bin/install-phantomjs.sh -o /tmp/install-phantomjs.sh
          sudo chmod a+rx /tmp/install-phantomjs.sh
          /tmp/install-phantomjs.sh
      - name: Install videos.sh
        run: |
          curl -L https://raw.githubusercontent.com/FETVGuide/videos/main/bin/videos.sh -o /usr/local/bin/videos.sh
          sudo chmod a+rx /usr/local/bin/videos.sh
      - name: VIDEOS j 1 10
        run: |
          /usr/local/bin/videos.sh j 1 10
          git add -A
          git commit -m "update videos j 1 10"
          git pull --rebase
          git push || true
